[build]
  dockerfile = "../compose/Dockerfile"
  [build.args]
    HONEYPOT_SNAPSHOT = "0x144d45af1181b35f2b11c4b1150d6cb16934c28093707fb97c911ff16b3fe609"
    HONEYPOT_VERSION = "3.0.0"
    HONEYPOT_CHAIN_NAME = "mainnet"
    HONEYPOT_CHECKSUM = "ad84d9b333308106e72c89c16906746c37bda69a1e83d0800b0543b47c1099d0"

[env]
  WEB3_CHAIN_ID = "1"
  APP_ADDRESS = "0xfDDF68726a28e418fA0c2a52c3134904a8c3e998"
  MACHINE_PATH = "/var/lib/cartesi-rollups-prt-node/snapshots/0x144d45af1181b35f2b11c4b1150d6cb16934c28093707fb97c911ff16b3fe609"
  RUST_LOG = "debug"
  STATE_DIR = "/var/lib/cartesi-rollups-prt-node/state"

[[mounts]]
  source = "honeypotv3_mainnet"
  destination = "/var/lib/cartesi-rollups-prt-node/state"
  initial_size = "2gb"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
