[build]
  dockerfile = "../compose/Dockerfile"
  [build.args]
    HONEYPOT_SNAPSHOT = "0xa0e299c59a356252c0723bd2cea8260547836aee5a1549dbcf2fc85b0d536845"
    HONEYPOT_VERSION = "3.0.0"
    HONEYPOT_CHAIN_NAME = "sepolia"
    HONEYPOT_CHECKSUM = "00d646bb4e9bc23e086bac283020c5d9e6f6824dbf9b1edba9c8c84a1a8d9caa"

[env]
  WEB3_CHAIN_ID = "11155111"
  APP_ADDRESS = "0xb72d7AfbE7afd35C82D1d0B3D9C714944ff5B7d8"
  MACHINE_PATH = "/var/lib/cartesi-rollups-prt-node/snapshots/0xa0e299c59a356252c0723bd2cea8260547836aee5a1549dbcf2fc85b0d536845"
  RUST_LOG = "debug"
  STATE_DIR = "/var/lib/cartesi-rollups-prt-node/state"

[[mounts]]
  source = "honeypotv3_sepolia"
  destination = "/var/lib/cartesi-rollups-prt-node/state"
  initial_size = "2gb"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
